services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8081:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=kbStores;User=sa;Password=YourStrong!Password123
    depends_on:
      - db
      - redis

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong!Password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  sql-data: