services:
  webapi:
    build:
      context: ./WebApi   # Points to the WebApi folder where Dockerfile is
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=kbstores;User=sa;Password=YourStrong!Password;
      - Redis__Configuration=redis:6379
    depends_on:
      - sqlserver
      - redis

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest  # Use the official image
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Password
      - MSSQL_PID=Developer
    volumes:
      - sqlserver_data:/var/opt/mssql


  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  sqlserver_data:
  redis_data: